import type { Campaign, TikTokPage } from "@/lib/types";

export const tiktokPages: TikTokPage[] = [
  {
    id: "nyc-rentals",
    handle: "@nycrentals",
    displayName: "NYC Rentals",
    avatarLabel: "NYC",
    market: "New York, NY",
    niche: "Luxury Rentals",
    followers: 178600,
    avgViews: 126400,
    engagementRate: 3.45,
    avgLikes: 1200,
    avgComments: 98,
    price: 325,
    deliveryDays: 2,
    audience: "82% US renters, 71% age 22-38",
    verified: true,
    topPerformer: true,
    saved: true,
    tags: ["Doorman", "Luxury", "NYC"],
    contentNotes: ["No prohibited content", "Brand safe", "US audience > 80%", "18+ audience"],
    weeklyViews: [28000, 62000, 54000, 77000, 69000, 104000, 132000, 114000, 119000, 151000, 138000, 163000],
    whopPlanId: process.env.NEXT_PUBLIC_DEMO_WHOP_PLAN_ID,
  },
  {
    id: "manhattan-leases",
    handle: "@manhattanleases",
    displayName: "Manhattan Leases",
    avatarLabel: "MHT",
    market: "New York, NY",
    niche: "Luxury Rentals",
    followers: 135400,
    avgViews: 92800,
    engagementRate: 3.02,
    avgLikes: 1010,
    avgComments: 83,
    price: 340,
    deliveryDays: 2,
    audience: "80% NYC renters with strong luxury intent",
    verified: true,
    topPerformer: false,
    saved: false,
    tags: ["Manhattan", "Luxury", "High-rise"],
    contentNotes: ["No prohibited content", "Brand safe", "Caption approval included", "Paid partnership disclosure required"],
    weeklyViews: [24000, 49000, 56000, 71000, 78000, 84000, 93000, 108000, 97000, 121000, 114000, 132000],
  },
  {
    id: "brooklyn-apts",
    handle: "@brooklynapts",
    displayName: "Brooklyn Apartments",
    avatarLabel: "BK",
    market: "New York, NY",
    niche: "Apartments",
    followers: 96100,
    avgViews: 62800,
    engagementRate: 2.81,
    avgLikes: 840,
    avgComments: 61,
    price: 275,
    deliveryDays: 3,
    audience: "79% tri-state renters, strong 1BR demand",
    verified: false,
    topPerformer: false,
    saved: false,
    tags: ["Walkups", "Brownstones", "Brooklyn"],
    contentNotes: ["No prohibited content", "Watermark accepted", "Caption approval included", "48h revision window"],
    weeklyViews: [19000, 42000, 38000, 47000, 61000, 58000, 69000, 64000, 72000, 83000, 79000, 88000],
  },
  {
    id: "queens-rentals",
    handle: "@queensrentals",
    displayName: "Queens Rentals",
    avatarLabel: "QNS",
    market: "New York, NY",
    niche: "Apartments",
    followers: 84300,
    avgViews: 59800,
    engagementRate: 2.88,
    avgLikes: 670,
    avgComments: 53,
    price: 260,
    deliveryDays: 3,
    audience: "77% NYC outer-borough renter audience",
    verified: false,
    topPerformer: false,
    saved: false,
    tags: ["Queens", "Apartments", "NYC"],
    contentNotes: ["No prohibited content", "Fair housing safe language required", "Creator approval before posting", "US audience > 80%"],
    weeklyViews: [17000, 28000, 36000, 43000, 51000, 55000, 62000, 69000, 73000, 76000, 81000, 86000],
  },
];

export const campaigns: Campaign[] = [
  {
    id: "1042",
    title: "Midtown 2BR Rental",
    pageId: "nyc-rentals",
    creatorHandle: "@nycrentals",
    creatorName: "NYC Rentals",
    status: "Creator Approval",
    paymentStatus: "Paid",
    paidAmount: 325,
    videoName: "midtown-2br-tour.mp4",
    videoDuration: "0:25",
  },
  {
    id: "1041",
    title: "Williamsburg 1BR",
    pageId: "brooklyn-apts",
    creatorHandle: "@brooklynapts",
    creatorName: "Brooklyn Apartments",
    status: "Video Upload",
    paymentStatus: "Paid",
    paidAmount: 275,
  },
  {
    id: "1040",
    title: "Tribeca 2BR",
    pageId: "manhattan-leases",
    creatorHandle: "@manhattanleases",
    creatorName: "Manhattan Leases",
    status: "Creator Approval",
    paymentStatus: "Paid",
    paidAmount: 340,
    videoName: "tribeca-2br.mp4",
    videoDuration: "0:29",
  },
  {
    id: "1039",
    title: "Upper East 3BR",
    pageId: "nyc-rentals",
    creatorHandle: "@nycrentals",
    creatorName: "NYC Rentals",
    status: "Posted",
    paymentStatus: "Paid",
    paidAmount: 325,
    videoName: "ues-3br-final.mp4",
    videoDuration: "0:27",
    postedOn: "Apr 24, 2026",
    views: 98400,
    likes: 3200,
    comments: 124,
    engagementRate: 3.37,
  },
  {
    id: "1038",
    title: "LIC Studio",
    pageId: "nyc-rentals",
    creatorHandle: "@nycrentals",
    creatorName: "NYC Rentals",
    status: "Completed",
    paymentStatus: "Released",
    paidAmount: 325,
    videoName: "lic-studio.mp4",
    videoDuration: "0:25",
    postedOn: "Apr 21, 2026",
    views: 112700,
    likes: 4100,
    comments: 156,
    engagementRate: 3.79,
  },
];
